In [4]:
# 1
#Create a list of 5 integers.Perform and print the result of the following operations:
#append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [5]:
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

Original list: [10, 20, 30, 40, 50]


In [6]:
# append() 
numbers.append(60)
print("After append(60):", numbers)


After append(60): [10, 20, 30, 40, 50, 60]


In [7]:
# extend() 
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)


After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]


In [8]:
# insert() 
numbers.insert(2, 25)  
print("After insert(2, 25):", numbers)



After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]


In [9]:
# Remove 
numbers.remove(40)
print("After remove(40):", numbers)




After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]


In [10]:
# pop() 
popped_value = numbers.pop()  
print("After pop():", numbers,"| Popped value:", popped_value)



After pop(): [10, 20, 25, 30, 50, 60, 70] | Popped value: 80


In [11]:
# clear()
temp_list = numbers.copy()  
numbers.clear()
print("After clear():", numbers," Before clear copy:", temp_list)


After clear(): []  Before clear copy: [10, 20, 25, 30, 50, 60, 70]


In [12]:
# Recreate list for next operations
numbers = [10, 20, 30, 20, 50]
# index() 
pos = numbers.index(20)
print("Index of 20:", pos)
# count() 
cnt = numbers.count(20)
print("Count of 20:", cnt)

# sort() 
numbers.sort()
print("After sort():", numbers)

# reverse() 
numbers.reverse()
print("After reverse():", numbers)


Index of 20: 1
Count of 20: 2
After sort(): [10, 20, 20, 30, 50]
After reverse(): [50, 30, 20, 20, 10]


In [13]:
# 2  
#Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.


In [14]:
students = ("Mohith", "Koushik", "Tarun")
print("Original tuple:", students)

Original tuple: ('Mohith', 'Koushik', 'Tarun')


In [15]:
# if i try to change
students[1] = "Nishi"  # This will raise an error

TypeError: 'tuple' object does not support item assignment

In [16]:
## Defining the above error
# Tuples in Python are immutable, which means once created, their elements cannot be changed.
# When we try to assign a new value to students[1], Python throws a TypeError.
# This behavior ensures that tuples remain constant and safe from accidental modification.

In [17]:
# 3rd 
#Create a set of integers with some duplicate values. Print the set and explain the output.


In [18]:
# Creating a set with duplicate values
numbers = {1, 2, 3, 2, 4, 3, 5}
print("Set of integers:", numbers)

Set of integers: {1, 2, 3, 4, 5}


In [19]:
# 4
#Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.


In [46]:
#  Creating a dictionary
student = {
    'name': 'mohith',
    'age': 19,
    'city': 'nellore'
}
student['age'] = 21
student['email'] = 'mohith17@gmail.com'
print("Final Dictionary:", student)


Final Dictionary: {'name': 'mohith', 'age': 21, 'city': 'nellore', 'email': 'mohith17@gmail.com'}


In [21]:
# 5
# Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.


In [22]:
age = int(input("Enter your age: "))
if age >= 18:
    print("You are eligible to vote")
else:
    print(" You are not eligible to vote yet")


Enter your age:  24


You are eligible to vote


In [23]:
# 6
# Given a 'marks' variable, print the grade:
# 90 and above: 'A'
# 75–89: 'B'
# 50–74: 'C'
# Below 50: 'Fail'


In [24]:
marks = int(input("Enter your marks: "))
# Determine grade
if marks >= 90:
    grade = 'A'
elif marks >= 75:
    grade = 'B'
elif marks >= 50:
    grade = 'C'
else:
    grade = 'Fail'

# result
print(f"Your grade is: {grade}")


Enter your marks:  80


Your grade is: B


In [25]:
# 7
# Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


In [31]:
num = int(input("Enter a number: "))
if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.").l
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")


Enter a number:  24


The number is positive.
It is also even.


In [28]:
# SECTION B
# NUMPY


In [29]:
# 8
# create 
# - A scalar using np.array(5)
# - A 1D array with values 1 to 5
# - A 2D array (2x3) with values from 10 to 60 in steps of 10


In [32]:
import numpy as np
scalar = np.array(5)
print("Scalar:", scalar)
print("Shape:", scalar.shape)

Scalar: 5
Shape: ()


In [ ]:
# A 1D array with values 1 to 5

In [33]:
one_d_array = np.array([1, 2, 3, 4, 5])
print("1D Array:", one_d_array)
print("Shape:", one_d_array.shape)


1D Array: [1 2 3 4 5]
Shape: (5,)


In [34]:
# A 2D array (2x3) with values from 10 to 60 in steps of 10

In [35]:
two_d_array = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:\n", two_d_array)
print("Shape:", two_d_array.shape)


2D Array:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)


In [36]:
# 9
# Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint()


In [37]:
import numpy as np
random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random Integer Array (0–100):")
print(random_array)


4x4 Random Integer Array (0–100):
[[ 68  11  89  14]
 [  7  64  23  49]
 [100  39  74  55]
 [ 92  31  46  19]]


In [38]:
# 10
# Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'

In [39]:
import pandas as pd
# Step 1: Create a 2D NumPy array of shape (3x3)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Step 2: Converting into DataFrame
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

# Step 3: Print the DataFrame
print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [41]:
# Explanation:
# np.array() creates a 3×3 matrix. 
# pd.DataFrame() converts it into a DataFrame. 
#columns=['A', 'B', 'C'] assigns custom column names.

In [43]:
# SECTION C
# PANDAS  


In [44]:
# 11 
#Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary


In [45]:

data = {
    'Name': ['krish', 'nikhil', 'koushik', 'tarun', 'nishi', 'sai', 'cherry', 'geetha', 'srinu', 'gayatri'],
    'Age': [25, 30, 22, 28, 35, 40, 29, 31, 27, 25],
    'City': ['Delhi', 'odisha', 'Chennai', 'Delhi', 'odisha', 'Chennai', 'Delhi', 'odisha', 'Chennai', 'Delhi'],
    'Salary': [50000, 60000, 55000, np.nan, 62000, 58000, 57000, 60000, np.nan, 50000]
}

df = pd.DataFrame(data)

print(" DataFrame Info:")
print(df.info())

print("\n Descriptive Statistics:")
print(df.describe())

print("\n Selected Columns ('Name' and 'City'):")
print(df[['Name', 'City']])

df_dropped = df.drop(columns=['City'])
print("\n DataFrame after dropping 'City':")
print(df_dropped)

mean_salary = df['Salary'].mean()
df['Salary'].fillna(mean_salary, inplace=True)
print("\n DataFrame after filling missing 'Salary' values with mean:")
print(df)

df_no_duplicates = df.drop_duplicates()
print("\n DataFrame after removing duplicate rows:")
print(df_no_duplicates)


 DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

 Descriptive Statistics:
             Age        Salary
count  10.000000      8.000000
mean   29.200000  56500.000000
std     5.245104   4535.573676
min    22.000000  50000.000000
25%    25.500000  53750.000000
50%    28.500000  57500.000000
75%    30.750000  60000.000000
max    40.000000  62000.000000

 Selected Columns ('Name' and 'City'):
      Name     City
0    krish    Delhi
1   nikhil   odisha
2  koushik  Chennai
3    tarun    Delhi
4    nishi   odisha
5      sai  Chennai
6   cherry    Delhi
7   geetha   odisha
8    srinu  Chennai
9  gayatri    Delhi

 DataFrame after dropp

C:\Users\hanum\AppData\Local\Temp\ipykernel_10936\1596210506.py:24: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(mean_salary, inplace=True)
